# Generated by Django 4.0.5 on 2023-11-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genreId', models.AutoField(primary_key=True, serialize=False)),
                ('nameOfGenre', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
